### ISSUE TITLE
품사 태깅 추가

### ISSUE THREAD

**Issue by dataminds** [bit2r/bitNLP#3]
사용자 사전 수정 기능에 품사를 태깅할 수 있는 기능 추가 부탁드립니다. 

예를 들어, 아래 문장에 등장하는 '일베'나 '펨코'와 같은 용어를 NNG로 등록할 수 있는 기능이 필요합니다. 

docs <- 
  c("좋은기사네요. 일베나 펨코같은 도태남의 의견이 주류의견인 척 이십대 남자들의 일반적인 의견이라고 포장이 되면 정상적인 남자들의 생각은 다 묻히겠구나 싶네요")
morpho_mecab(docs,  type = "morpheme")

 VA     ETM     NNG  VCP+EF      SF 
   "좋"    "은"  "기사"  "네요"     "." 
    NNG      VV      EC UNKNOWN      VA 
   "일"    "베"    "나"  "펨코"    "같" 
    ETM     NNG     NNG     JKG     NNG 
   "은"  "도태"    "남"    "의"  "의견" 
    JKS     NNG     NNG VCP+ETM     NNB 
   "이"  "주류"  "의견"    "인"    "척" 
     NR      NR    NNBC     NNG     XSN 
   "이"    "십"    "대"  "남자"    "들" 
    JKG     NNG     XSN VCP+ETM     NNG 
   "의"  "일반"    "적"    "인"  "의견" 
    VCP      EC     NNG     JKS      VV 
   "이"  "라고"  "포장"    "이"    "되" 
     EC     NNG     XSN VCP+ETM     NNG 
   "면"  "정상"    "적"    "인"  "남자" 
    XSN     JKG     NNG      JX     MAG 
   "들"    "의"  "생각"    "은"    "다" 
     VV      EP      EC      VX      EC 
 "묻히"    "겠"  "구나"    "싶"  "네요"

**Comment by choonghyunryu** [comment]
@dataminds,

계획에 있는데, 진행을 못하고 있습니다.
패키지 유지보수 대상 중에 우선순위로 놓고, 반영토록하겠습니다.

**Comment by choonghyunryu** [comment]
@dataminds,
 
1.3.7.9000 버전에 기능을 구현했습니다.
늦어서 죄송합니다.

**Comment by choonghyunryu** [comment]
1.4.0에서 시스템사전 혹은 사용자 사전에 선택적으로 적용할 수 있는 기능을 구현하였습니다.
